INSERT INTO Location VALUES (6001, "Kuala Lumpur");
INSERT INTO Location(location_name) VALUES ("Klang");
INSERT INTO Location(location_name) VALUES ("Ipoh");
INSERT INTO Location(location_name) VALUES ("Butterworth");
INSERT INTO Location(location_name) VALUES ("Johor Bahru");
INSERT INTO Location(location_name) VALUES ("George Town");
INSERT INTO Location(location_name) VALUES ("Petaling Jaya");
INSERT INTO Location(location_name) VALUES ("Kuantan");
INSERT INTO Location(location_name) VALUES ("Shah Alam");
INSERT INTO Location(location_name) VALUES ("Kota Bharu");
INSERT INTO Location(location_name) VALUES ("Melaka");
INSERT INTO Location(location_name) VALUES ("Kota Kinabalu");
INSERT INTO Location(location_name) VALUES ("Seremban");
INSERT INTO Location(location_name) VALUES ("Sadakan");
INSERT INTO Location(location_name) VALUES ("Sungai Petani");
INSERT INTO Location(location_name) VALUES ("Kuching");
INSERT INTO Location(location_name) VALUES ("Kuala Terengganu");
INSERT INTO Location(location_name) VALUES ("Alor Setar");
INSERT INTO Location(location_name) VALUES ("Putrajaya");
INSERT INTO Location(location_name) VALUES ("Kangar");
INSERT INTO Location(location_name) VALUES ("Labuan");
INSERT INTO Location(location_name) VALUES ("Pasir Mas");
INSERT INTO Location(location_name) VALUES ("Tumpat");
INSERT INTO Location(location_name) VALUES ("Ketereh");
INSERT INTO Location(location_name) VALUES ("Kampung Lemal");
INSERT INTO Location(location_name) VALUES ("Pulai Chondong");