INSERT INTO Location VALUES (6001, "Kuala Lumpur");
INSERT INTO Location VALUES (6002, "Klang");
INSERT INTO Location VALUES (6003, "Ipoh");
INSERT INTO Location VALUES (6004, "Butterworth");
INSERT INTO Location VALUES (6005, "Johor Bahru");
INSERT INTO Location VALUES (6006, "George Town");
INSERT INTO Location VALUES (6007, "Petaling Jaya");
INSERT INTO Location VALUES (6008, "Kuantan");
INSERT INTO Location VALUES (6009, "Shah Alam");
INSERT INTO Location VALUES (6010, "Kota Bharu");
INSERT INTO Location VALUES (6011, "Melaka");
INSERT INTO Location VALUES (6012, "Kota Kinabalu");
INSERT INTO Location VALUES (6013, "Seremban");
INSERT INTO Location VALUES (6014, "Sadakan");
INSERT INTO Location VALUES (6015, "Sungai Petani");
INSERT INTO Location VALUES (6016, "Kuching");
INSERT INTO Location VALUES (6017, "Kuala Terengganu");
INSERT INTO Location VALUES (6018, "Alor Setar");
INSERT INTO Location VALUES (6019, "Putrajaya");
INSERT INTO Location VALUES (6020, "Kangar");
INSERT INTO Location VALUES (6021, "Labuan");
INSERT INTO Location VALUES (6022, "Pasir Mas");
INSERT INTO Location VALUES (6023, "Tumpat");
INSERT INTO Location VALUES (6024, "Ketereh");
INSERT INTO Location VALUES (6025, "Kampung Lemal");
INSERT INTO Location VALUES (6026, "Pulai Chondong");